name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build sdist and wheel
        run: |
          python -m build
      - name: Publish to PyPI
        if: ${{ env.PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ env.PYPI_API_TOKEN }}
          skip_existing: true
      - name: Upload artifacts (always)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
